<!DOCTYPE html>
<!--[if lt IE 8]>      <html lang="zh-CN" class="no-js lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="zh-CN" class="no-js lt-ie10 lt-ie9 ie8"> <![endif]-->
<!--[if IE 9]>         <html lang="zh-CN" class="no-js lt-ie10 ie9"> <![endif]-->
<!--[if gt IE 9]><!--> <html lang="zh-CN" class="no-js"> <!--<![endif]-->
	<head>
		<meta charset="utf-8" />
        <title><?=$this->placeholder->block('title', 'EvaEngine Admin');?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<?
$this->assets
->collection('headerCss')
->addCss('/vendor/bootstrap/dist/css/bootstrap.css')
->addCss('/vendor/fontawesome3/css/font-awesome.css')
->addCss('/vendor/ace-admin/css/ace-fonts.css')
->addCss('/vendor/ace-admin/css/ace.min.css')
->addCss('/vendor/ace-admin/css/ace-skins.min.css')
->addCss('/vendor/ace-admin/css/ace-rtl.min.css')
->addCss('/admin/css/typeaheadjs.css')
;
$this->assets->outputCss('headerCss');
?>
		<!--[if IE 7]>
        <link rel="stylesheet" href="<?=$this->url->getStatic('/vendor/fontawesome3/css/font-awesome-ie7.css')?>" />
		<![endif]-->
		<!--[if lte IE 8]>
        <link rel="stylesheet" href="<?=$this->url->getStatic('/vendor/ace-admin/css/ace-ie.min.css')?>" />
		<![endif]-->
		<!--[if lt IE 9]>
        <script src="<?=$this->url->getStatic('/vendor/html5shiv/dist/html5shiv.min.js')?>"></script>
        <script src="<?=$this->url->getStatic('/vendor/respond/dest/respond.min.js')?>"></script>
        <![endif]-->

        <script type="text/javascript" src="<?=$this->url->getStatic('/vendor/requirejs/require.js');?>"></script>
        <script>
        if (typeof define === "function" && define.amd) {
            require.config({
                urlArgs: "v=<?=$this->url->getVersion()?>",
                baseUrl: "<?=$this->config->staticBaseUri?>/"
            });
        }
        </script>
<?
$this->assets
->collection('headerJs')
//->addJs('/admin/js/require-config.js')
->addJs('/require-config.js')
->addJs('/admin/js/require-shim.js');

$this->assets->outputJs('headerJs');
?>
	</head>
	<body>
		<div class="navbar navbar-default" id="navbar">
			<div class="navbar-container" id="navbar-container">
				<div class="navbar-header pull-left">
					<a href="#" class="navbar-brand">
						<small>
							<i class="icon-leaf"></i>
                            <?=$this->tag->_('EvaEngine');?>	
						</small>
					</a><!-- /.brand -->
				</div><!-- /.navbar-header -->

				<div class="navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">

						<li class="light-blue">
                        <?if(isset($authIdentity)):?>
							<a data-toggle="dropdown" href="#" class="dropdown-toggle">
                                <img class="nav-user-photo" src="<?=$this->tag->gravatar($authIdentity['email'])?>" alt="" />
								<span class="user-info">
									<small>Welcome,</small>
                                    <?=$authIdentity['username']?>
								</span>

								<i class="icon-caret-down"></i>
							</a>
                        <?endif?>

							<ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                                <!--
								<li>
									<a href="#">
										<i class="icon-cog"></i>
										Settings
									</a>
								</li>

								<li>
									<a href="#">
										<i class="icon-user"></i>
										Profile
									</a>
								</li>
                                -->

								<li class="divider"></li>

								<li>
									<a href="/logout">
										<i class="icon-off"></i>
										Logout
									</a>
								</li>
							</ul>
						</li>
					</ul><!-- /.ace-nav -->
				</div><!-- /.navbar-header -->
			</div><!-- /.container -->
		</div>

		<div class="main-container" id="main-container">
			<div class="main-container-inner">
				<a class="menu-toggler" id="menu-toggler" href="#">
					<span class="menu-text"></span>
				</a>

				<div class="sidebar" id="sidebar">
					<div class="sidebar-shortcuts" id="sidebar-shortcuts">
						<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
							<a class="btn btn-success" href="/admin/dashboard">
								<i class="icon-signal"></i>
							</a>

                            <a class="btn btn-info" href="/admin/post/create">
								<i class="icon-pencil"></i>
							</a>

                            <a class="btn btn-warning" href="/admin/user">
								<i class="icon-group"></i>
							</a>

                            <a class="btn btn-danger" href="/admin/media/upload">
								<i class="icon-upload"></i>
							</a>
						</div>

						<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
							<span class="btn btn-success"></span>

							<span class="btn btn-info"></span>

							<span class="btn btn-warning"></span>

							<span class="btn btn-danger"></span>
						</div>
					</div><!-- #sidebar-shortcuts -->

					<ul class="nav nav-list">
                        <?$moduleManager = $this->moduleManager;$modules = $moduleManager->getModules();?>
                        <?foreach($modules as $moduleName => $module):?>
                        <?$moduleManager->getModuleAdminMenu($moduleName)?>
                        <?endforeach?>
					</ul><!-- /.nav-list -->

					<div class="sidebar-collapse" id="sidebar-collapse">
						<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
					</div>
				</div>

				<div class="main-content">
                    <?=$this->tag->flashOutput()?>
                    <?=$this->getContent()?>

				</div><!-- /.main-content -->


			</div><!-- /.main-container-inner -->

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="icon-double-angle-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->
<?
$this->assets
->collection('footerJs')
    ->addJs('/admin/js/default-action.js');
$this->assets->outputJs('footerJs');
?>
	</body>
</html>
