<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
		<meta charset="utf-8" />
        <title><?=$this->placeholder->block('title', 'EvaEngine Admin');?></title>

		<meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <?
            $this->assets
            ->collection('headerCss')
            ->addCss('/vendor/bootstrap/dist/css/bootstrap.css')
            ->addCss('/vendor/fontawesome3/css/font-awesome.css')
            ->addCss('/vendor/ace-admin/css/ace-fonts.css')
            ->addCss('/vendor/ace-admin/css/ace.min.css')
            ->addCss('/vendor/ace-admin/css/ace-part2.min.css')
            ->addCss('/vendor/ace-admin/css/ace-rtl.min.css');
            $this->assets->outputCss('headerCss');
        ?>
        <!--[if IE 7]>
        <link rel="stylesheet" href="<?=$this->url->getStatic('/vendor/fontawesome3/css/font-awesome-ie7.css')?>" />
        <![endif]-->
        <!--[if lte IE 8]>
        <link rel="stylesheet" href="<?=$this->url->getStatic('/vendor/ace-admin/css/ace-ie.min.css')?>" />
        <![endif]-->
        <!--[if lt IE 9]>
        <script src="<?=$this->url->getStatic('/vendor/html5shiv/dist/html5shiv.min.js')?>"></script>
        <script src="<?=$this->url->getStatic('/vendor/respond/dest/respond.min.js')?>"></script>
        <![endif]-->

        <script type="text/javascript" src="<?=$this->url->getStatic('/vendor/requirejs/require.js');?>"></script>
        <script>
            if (typeof define === "function" && define.amd) {
                require.config({
                    urlArgs: "v=<?=$this->url->getVersion()?>",
                    baseUrl: "<?=$this->config->staticBaseUri?>/"
                });
            }
        </script>
        <?
        $this->assets
            ->collection('headerJs')
//->addJs('/admin/js/require-config.js')
            ->addJs('/require-config.js')
            ->addJs('/admin/js/require-shim.js');

        $this->assets->outputJs('headerJs');
        ?>
    </head>

    <body class="login-layout">
        <div class="main-container">
            <div class="main-content">
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        <div class="login-container">
                            <div class="center">
                                <h1>
                                    <i class="icon-leaf green"></i>
                                    <span class="white"><?=$this->tag->_('EvaEngine')?></span>
                                </h1>
                                <h4 class="blue">&copy; WallstreetCN</h4>
                            </div>

                            <div class="space-6"></div>

                            <div class="position-relative">
                                <?=$this->tag->flashOutput()?>
                                <?=$this->getContent()?>
                            </div><!-- /position-relative -->
                        </div>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div>
        </div><!-- /.main-container -->

        <!-- basic scripts -->

<!--        --><?//
//        $this->assets
//        ->collection('footerJs')
//        ->addJs('/vendor/bootstrap/dist/js/bootstrap.js')
//        ->addJs('/vendor/parsleyjs/dist/parsley.js')
//        ->addJs('/vendor/parsleyjs/dist/parsley.remote.js')
//        ;
//        $this->assets->outputJs('footerJs');
//    ?>



        <script type="text/javascript">
            require(['jquery','jquery.parsley','parsley.remote','bootstrap'],function($){
                function show_box(id) {
                    $('.widget-box.visible').removeClass('visible');
                    $('#' + id).addClass('visible');
                }
                //忘记密码和注册，写在dom中的onclick属性下，因此加入在window下
                window.show_box = show_box
                $(document).ready(function () {
                    $('form').parsley({
                        successClass: "has-success",
                        errorClass: "has-error",
                        classHandler: function (el) {
                            return el.$element.closest(".form-group");
                        },

                        errorsWrapper: "<span class='help-block'></span>",
                        errorTemplate: "<span></span>"
                    });

                });
            })

        </script>

<!--        --><?//
//        $this->assets
//            ->collection('footerJs')
//            ->addJs('/admin/js/default-action.js');
//        $this->assets->outputJs('footerJs');
//        ?>
<!--        </body>-->
    </html>
